# Generated by Django 4.2.4 on 2023-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('prise', models.CharField(max_length=8)),
                ('color', models.CharField(max_length=15)),
                ('time', models.IntegerField()),
                ('reviews', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=15)),
                ('genre', models.CharField(choices=[('Драма', 'Драма'), ('Триллер', 'Триллер'), ('Шоу', 'Шоу'), ('Концерт', 'Концерт'), ('Ужасы', 'Ужасы'), ('Детектив', 'Детектив'), ('Фантастический', 'Фантастический')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
