# Generated by Django 4.2.4 on 2023-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='color',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='year',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
