# Generated by Django 4.2.4 on 2023-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_remove_tvshow_color_tvshow_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='prise',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='price',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
